import 'package:flutter/material.dart';

class AdminTimeTableProvider with ChangeNotifier {
  List<Map<String, dynamic>> _items = [
    {
      'day': 'Saturday',
      'bell': '8 - 10',
      'items': [
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '256'},
      ],
    },
    {
      'day': 'Saturday',
      'bell': '10 - 12',
      'items': [
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '257'},
      ],
    },
    {
      'day': 'Saturday',
      'bell': '14 - 16',
      'items': [
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '258'},
      ],
    },
    {
      'day': 'Saturday',
      'bell': '16 - 18',
      'items': [
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '259'},
      ],
    },
    {
      'day': 'Sunday',
      'bell': '8 - 10',
      'items': [
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '260'},
      ],
    },
    {
      'day': 'Sunday',
      'bell': '10 - 12',
      'items': [
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '261'},
      ],
    },
    {
      'day': 'Sunday',
      'bell': '14 - 16',
      'items': [
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '262'},
      ],
    },
    {
      'day': 'Sunday',
      'bell': '16 - 18',
      'items': [
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '263'},
      ],
    },
    {
      'day': 'Monday',
      'bell': '8 - 10',
      'items': [
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '264'},
      ],
    },
    {
      'day': 'Monday',
      'bell': '10 - 12',
      'items': [
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '265'},
      ],
    },
    {
      'day': 'Monday',
      'bell': '14 - 16',
      'items': [
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '266'},
      ],
    },
    {
      'day': 'Monday',
      'bell': '16 - 18',
      'items': [
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '267'},
      ],
    },
    {
      'day': 'Tuesday',
      'bell': '8 - 10',
      'items': [
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '268'},
      ],
    },
    {
      'day': 'Tuesday',
      'bell': '10 - 12',
      'items': [
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '269'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '269'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '269'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '269'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '269'},
      ],
    },
    {
      'day': 'Tuesday',
      'bell': '14 - 16',
      'items': [
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '270'},
      ],
    },
    {
      'day': 'Tuesday',
      'bell': '16 - 18',
      'items': [
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '271'},
      ],
    },
    {
      'day': 'Wednesday',
      'bell': '8 - 10',
      'items': [
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
        {'master': 'Tanha', 'course': 'Algorithm', 'classNumber': '272'},
      ],
    },
    {
      'day': 'Wednesday',
      'bell': '10 - 12',
      'items': [
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
        {'master': 'Moalemi', 'course': 'CPU', 'classNumber': '273'},
      ],
    },
    {
      'day': 'Wednesday',
      'bell': '14 - 16',
      'items': [
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
        {'master': 'Zolfi', 'course': 'Architecture', 'classNumber': '274'},
      ],
    },
    {
      'day': 'Wednesday',
      'bell': '16 - 18',
      'items': [
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
        {'master': 'Agdasi', 'course': 'AI', 'classNumber': '275'},
      ],
    },
  ];

  List<Map<String, dynamic>> get getItems {
    return [..._items];
  }
}
